### ISSUE TITLE
[FEAT] User authentication

### ISSUE THREAD

**Issue by maceteligolden** [dev-huddle/InventoryAI#1]
users should be able to login and register on the platform

**Comment by maceteligolden** [comment]
# Authentication and Authorization Documentation

## Introduction

### **What is Authentication and Authorization?**
Authentication and authorization are fundamental concepts in securing applications:
- **Authentication**: The process of verifying a user's identity. For example, checking if a provided email and password match a registered account.
- **Authorization**: The process of verifying what actions a user is allowed to perform. For example, ensuring only admins can delete resources.

### **What is Stateful Authentication?**
Stateful authentication refers to maintaining the user's session on the server side, often by storing tokens (like refresh tokens) in a persistent store such as a database. This approach ensures:
- **Enhanced Security**: Tokens stored server-side can be invalidated instantly, minimizing the risk of misuse.
- **Control**: Session data is managed by the server, allowing for better oversight and compliance.

## Technology Stack

This feature is implemented using the following tools:
- **Express**: A lightweight and fast Node.js framework for building REST APIs.
- **TypeScript**: A typed superset of JavaScript that enhances code reliability and readability.
- **Bcrypt**: A library for hashing passwords securely.
- **Jsonwebtoken**: A library for generating and verifying JSON Web Tokens (JWT) used for authentication.
- **MongoDB**: A NoSQL database for storing user data and refresh tokens.

## Constraints and Design Decisions

### **No Cache Layer**
This implementation avoids using a cache layer (like Redis). Instead, refresh tokens are stored in the database. While caching can improve performance, the absence of a cache layer simplifies deployment and reduces dependencies, making the solution easier to manage.

### **Refresh Token Storage**
Refresh tokens are stored in the database to:
- Allow server-side control over token validity.
- Enable token revocation during logout or account compromise.

---

## Endpoints

### **1. Register**

#### **URL**
`POST /api/auth/register`

#### **Request Body**
```json
{
  "firstname": "John",
  "lastname": "Doe",
  "email": "johndoe@example.com",
  "password": "securePassword123"
}
```

#### **Response**
- **201 Created**:
  ```json
  {
    "message": "User registered successfully"
  }
  ```

#### **Errors**
- **400 Bad Request**: If required fields are missing or validation fails.
  ```json
  {
    "message": "Validation error"
  }
  ```
- **409 Conflict**: If the email is already registered.
  ```json
  {
    "message": "User already exists"
  }
  ```

---

### **2. Login**

#### **URL**
`POST /api/auth/login`

#### **Request Body**
```json
{
  "email": "johndoe@example.com",
  "password": "securePassword123"
}
```

#### **Response**
- **200 OK**:
  ```json
  {
    "accessToken": "<jwt-access-token>",
    "refreshToken": "<jwt-refresh-token>"
  }
  ```

#### **Errors**
- **404 Not Found**: If the email is not registered.
  ```json
  {
    "message": "User not found"
  }
  ```
- **401 Unauthorized**: If the password is incorrect.
  ```json
  {
    "message": "Invalid credentials"
  }
  ```

---

### **3. Refresh Token**

#### **URL**
`POST /api/auth/refresh`

#### **Request Body**
```json
{
  "refreshToken": "<jwt-refresh-token>"
}
```

#### **Response**
- **200 OK**:
  ```json
  {
    "accessToken": "<new-jwt-access-token>"
  }
  ```

#### **Errors**
- **401 Unauthorized**: If no refresh token is provided.
  ```json
  {
    "message": "Refresh token required"
  }
  ```
- **403 Forbidden**: If the refresh token is invalid or expired.
  ```json
  {
    "message": "Invalid or expired refresh token"
  }
  ```

---

### **4. Logout**

#### **URL**
`POST /api/auth/logout`

#### **Request Body**
```json
{
  "refreshToken": "<jwt-refresh-token>"
}
```

#### **Response**
- **200 OK**:
  ```json
  {
    "message": "Logged out successfully"
  }
  ```

#### **Errors**
- **400 Bad Request**: If no refresh token is provided.
  ```json
  {
    "message": "Refresh token required"
  }
  ```
- **404 Not Found**: If the refresh token is not associated with any user.
  ```json
  {
    "message": "Invalid refresh token"
  }
  ```

---

### Task Checklist

- [ ] Define the `register` endpoint with proper validation and error handling.
- [ ] Implement the `login` endpoint to authenticate users and generate tokens.
- [ ] Create the `refresh` endpoint to handle token renewal.
- [ ] Develop the `logout` endpoint to invalidate refresh tokens.
- [ ] Store refresh tokens securely in the database.
- [ ] Ensure all error messages follow the documented structure.

### Additional Notes
Refer to the implementation plan above to guide development. Raise any blockers or questions as GitHub issues linked to this task.
